#!/usr/bin/env python3

from fastmcp import FastMCP
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

mcp = FastMCP("Calculator MCP Server")


@mcp.tool()
def divide(a: float, b: float) -> float:
    """
    Divide a by b and return the result.
    
    Raises:
        ValueError: If b is zero
    """
    if b == 0:
        raise ValueError("Cannot divide by zero")
    return a / b


@mcp.tool()
def use_hybrid_model(task: str, s3_keys: list[str]) -> dict:
    return {'answer': ''}


@mcp.tool()
def use_surrogate_model(task: str, s3_keys: list[str]) -> dict:
    """
    Answers questions based on the content of user-provided scientific papers. 
    This tool allows users to query specific documents they've uploaded, retrieving insights 
    
    
    Args:
        task (str): The user's question about the uploaded papers.
        s3_keys (list[str]): The list of S3 keys for the uploaded papers.
        config (RunnableConfig): The configuration for the runnable.


    Returns:
        dict: A dictionary containing the answer generated by the LLM and metadata 
              about the request (e.g., model used, token count).  
              Returns an error message if no papers are provided or if data extraction fails.
    """
    logger.info('Running explore_my_papers tool...')
    logger.info(f'task: {task}')
    try:
        a=3
        return a
    except Exception as e:
        logger.error(f'explore_my_papers ERROR: {e}')
        return {'answer': 'Could not extract any data from uploaded papers.'}


# _______ plots:
@mcp.tool()
def orig_data_plots(task: str, s3_keys: list[str]) -> dict:
    return {'answer': ''}


@mcp.tool()
def orig_data_plots(task: str, s3_keys: list[str]) -> dict:
    return {'answer': ''}


@mcp.tool()
def predict_models_plots(task: str, s3_keys: list[str]) -> dict:
    return {'answer': ''}


@mcp.tool()
def calibration_all_data_plots(task: str, s3_keys: list[str]) -> dict:
    return {'answer': ''}


@mcp.tool()
def calibration_incomplete_data_plots(task: str, s3_keys: list[str]) -> dict:
    return {'answer': ''}


if __name__ == "__main__":
    mcp.run(transport="http", host="0.0.0.0", port=7331, path="/mcp")